//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;peep&gt;
        ///  &lt;name&gt;Bach&lt;/name&gt;
        ///  &lt;name&gt;Fred&lt;/name&gt;
        ///  &lt;name&gt;Jamie&lt;/name&gt;
        ///  &lt;name&gt;Hendo&lt;/name&gt;
        ///  &lt;name&gt;Justin&lt;/name&gt;
        ///  &lt;name&gt;Sobjack&lt;/name&gt;
        ///  &lt;name&gt;Celine&lt;/name&gt;
        ///  &lt;name&gt;Ina&lt;/name&gt;
        ///  &lt;name&gt;Kouri&lt;/name&gt;
        ///  &lt;name&gt;Shane&lt;/name&gt;
        ///  &lt;name&gt;Drew&lt;/name&gt;
        ///  &lt;name&gt;Chzuck&lt;/name&gt;
        ///  &lt;name&gt;Brian&lt;/name&gt;
        ///  &lt;name&gt;Eric&lt;/name&gt;
        ///  &lt;name&gt;Ambrozy&lt;/name&gt;
        ///  &lt;name&gt;Marz&lt;/name&gt;
        ///  &lt;name&gt;Irwin&lt;/name&gt;
        ///  &lt;name&gt;Billy&lt;/name&gt;
        ///  &lt;name&gt;Bersche&lt;/name&gt;
        ///  &lt;name&gt;Brad&lt;/name&gt;
        ///  &lt;name&gt;Tom&lt;/name&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NameList {
            get {
                return ResourceManager.GetString("NameList", resourceCulture);
            }
        }
    }
}
